ScreenCritic/urls.py
from django.urls import path
from ScreenCritic import views

app_name = 'ScreenCritic'

urlpatterns = [
    path('', views.home, name='home'),  
    path('home/', views.home, name='home'),
    path('login_register/', views.login_register, name = 'login_register'),
    path('logout/', views.user_logout, name = "user_logout"),
    path('delete_account/', views.deleteuser, name = 'delete_account'),

    
    # TV Shows
    path('tv/', views.tv_list, name='tv_list'),
    path('tv/<slug:slug>/', views.media_detail, {'media_type': 'TV Show'}, name='tv_detail'),
    path('tv/<slug:slug>/review/', views.media_review, {'media_type': 'TV Show'}, name='tv_review'),

    # Movies
    path('movies/', views.movie_list, name='movie_list'),
    path('movies/<slug:slug>/', views.media_detail, {'media_type': 'Movie'}, name='movie_detail'),
    path('movies/<slug:slug>/review/', views.media_review, {'media_type': 'Movie'}, name='movie_review'),

    # Games
    path('games/', views.game_list, name='game_list'),
    path('games/<slug:slug>/', views.media_detail, {'media_type': 'Game'}, name='game_detail'),
    path('games/<slug:slug>/review/', views.media_review, {'media_type': 'Game'}, name='game_review'),

    path('review/<int:review_id>/like/', views.like_review, name='like_review'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.profile_view, name='profile_by_username'),

    path('search/', views.live_search, name='live_search'),

    path('notifications/', views.get_notifications, name='get_notifications'),
    path('notifications/<int:subscription_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('toggle-subscription/<int:media_id>/', views.toggle_subscription, name='toggle_subscription'),
]

WAD2_TEAM5A_PROJECT/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from ScreenCritic import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='ScreenCritic/change_password.html',
        success_url='/ScreenCritic/profile'
    ), name='password_change'),
    path('admin/', admin.site.urls),
    path('ScreenCritic/', include('ScreenCritic.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ScreenCritic/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)
    profile_picture = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.username

class Genre(models.Model):
    genre_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
    
class Media(models.Model):
    media_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    type = models.CharField(max_length=20)
    description = models.TextField(blank=True, null=True)
    cover_image = models.ImageField(upload_to='cover_images/', blank=True, null=True)
    duration = models.IntegerField(blank=True, null=True)
    release_date = models.DateTimeField()
    genres = models.ManyToManyField(Genre, related_name="media")
    creator = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug: #only generate slug if not already defined
            original_slug = slugify(self.title)
            slug = original_slug
            counter = 1
            while Media.objects.filter(slug=slug).exists(): #if the same slug already exists then add counter
                slug = f"{original_slug}_{counter}"
                counter += 1
            self.slug = slug
        super(Media, self).save(*args, **kwargs)

    @property
    def average_rating(self):
        return Review.objects.filter(media_id=self).aggregate(models.Avg('rating'))['rating__avg'] or 0

    def __str__(self):
        return self.title

class Review(models.Model):
    review_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    review = models.TextField(blank=True, null=True)
    rating = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    @property
    def total_likes(self):
        return ReviewLike.objects.filter(review=self).count()

    def __str__(self):
        return self.user.username + "'s review of " + self.media.title
    
class ReviewLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    date_liked = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'review'),)

    def __str__(self):
        return f"{self.user.username} liked {self.review}"
    
class UserMediaSubscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    is_released = models.BooleanField(default=False)  #set to True when media is released
    read_by_user = models.BooleanField(default=False)  #set to True when user clicks/views the notification
    notification_date = models.DateTimeField(null=True, blank=True)  #when the notification was created

    class Meta:
        unique_together = (('user', 'media'),)

    def __str__(self):
        return self.user.username + " subscribed to " + self.media.title
    
class UserFavouriteGenre(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'genre'),)

    def __str__(self):
        return f"{self.user.username} loves {self.genre.name}"

ScreenCritic/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils.timezone import now
from django.db.models import Avg, Count, Q, Subquery, OuterRef
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.templatetags.static import static
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.http import require_GET
from .templatetags.custom_filters import route_name
from .utils import resolve_image
from django.core.paginator import Paginator

from .forms import (
    LoginForm,
    ProfileEditForm,
    RegisterForm,
    ReviewForm,
    UserDeleteForm
)
from .models import (
    Genre,
    Media, 
    Review,
    ReviewLike,
    UserFavouriteGenre,
    UserProfile,
    UserMediaSubscription
)

def home(request): #render the home page
    #get top rated reviews ordered by rating and likes
    top_reviews = Review.objects.annotate(like_count=Count('reviewlike')).order_by('-like_count','-rating')[:25]

    #get upcoming media ordered by release date (starting from tomorrow)
    tomorrow = timezone.now().date() + timezone.timedelta(days=1)
    upcoming_media = Media.objects.filter(release_date__gte=tomorrow).order_by('release_date')[:40]

    #get trending movies based on average rating
    trending_movies = Media.objects.filter(type='Movie').annotate(
        avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]

    #get trending TV shows based on average rating
    trending_shows = Media.objects.filter(type='TV Show', slug__isnull=False, slug__gt='').annotate(
        avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]

    #get trending games based on average rating
    trending_games = Media.objects.filter(type='Game').annotate(
        avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]

    #prepare context data for template
    context = {
        'trending_movies': trending_movies,
        'trending_shows': trending_shows,
        'trending_games': trending_games,
        'upcoming_media': upcoming_media,
        'top_reviews': top_reviews,
    }

    return render(request, 'ScreenCritic/index.html', context)

def movie_list(request): #display list of movies and related movie content
    movies = Media.objects.filter(type='Movie').order_by('-release_date') #get all movies ordered by release date
    suggested_movies = []
    if request.user.is_authenticated:
        favorite_genres = UserFavouriteGenre.objects.filter(user=request.user).values_list('genre', flat=True) #get user's favorite genres
        if favorite_genres.exists():
            suggested_movies = Media.objects.filter( #get suggested movies based on user's favorite genres
                type='Movie',
                genres__in=favorite_genres
            ).annotate(avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]

    trending_movies = Media.objects.filter(type='Movie').annotate( #get trending movies based on ratings
        avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]
    movies_alphabetically = Media.objects.filter(type='Movie').order_by('title') #get movies sorted alphabetically
    movies_by_genre = {} #organize movies by genre

    for movie in Media.objects.filter(type='Movie').prefetch_related('genres'): #group movies by their genres
        for genre in movie.genres.all():
            movies_by_genre.setdefault(genre.name, []).append(movie)

    context = { #prepare context data for template
        'media_list': movies,
        'media_type': 'Movies',
        'trending_movies': trending_movies,
        'movies_alphabetically': movies_alphabetically,
        'movies_by_genre': movies_by_genre,
        'suggested_movies': suggested_movies,
    }
    return render(request, 'ScreenCritic/media.html', context)

def tv_list(request): #display list of TV shows and related TV content
    shows = Media.objects.filter(type='TV Show', slug__isnull=False, slug__gt='').order_by('-release_date') #get all TV shows ordered by release date
    suggested_shows = []
    if request.user.is_authenticated:
        favorite_genres = UserFavouriteGenre.objects.filter(user=request.user).values_list('genre', flat=True) #get user's favorite genres
        if favorite_genres.exists():
            suggested_shows = Media.objects.filter( #get suggested shows based on user's favorite genres
                type='TV Show',
                genres__in=favorite_genres,
                slug__isnull=False,
                slug__gt=''
            ).annotate(avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]

    trending_shows = Media.objects.filter(type='TV Show', slug__isnull=False, slug__gt='').annotate( #get trending shows based on ratings
        avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]
    shows_alphabetically = Media.objects.filter(type='TV Show', slug__isnull=False, slug__gt='').order_by('title') #get shows sorted alphabetically
    shows_by_genre = {} #organize shows by genre

    for show in Media.objects.filter(type='TV Show', slug__isnull=False, slug__gt='').prefetch_related('genres'): #group shows by their genres
        for genre in show.genres.all():
            shows_by_genre.setdefault(genre.name, []).append(show)

    context = { #prepare context data for template
        'media_list': shows,
        'media_type': 'TV Shows',
        'trending_movies': trending_shows,
        'movies_alphabetically': shows_alphabetically,
        'movies_by_genre': shows_by_genre,
        'suggested_movies': suggested_shows,
    }
    return render(request, 'ScreenCritic/media.html', context)

def game_list(request): #display list of games and related game content
    games = Media.objects.filter(type='Game').order_by('-release_date') #get all games ordered by release date
    suggested_games = []
    if request.user.is_authenticated:
        favorite_genres = UserFavouriteGenre.objects.filter(user=request.user).values_list('genre', flat=True) #get user's favorite genres
        if favorite_genres.exists():
            suggested_games = Media.objects.filter( #get suggested games based on user's favorite genres
                type='Game',
                genres__in=favorite_genres
            ).annotate(avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]

    trending_games = Media.objects.filter(type='Game').annotate( #get trending games based on ratings
        avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]
    games_alphabetically = Media.objects.filter(type='Game').order_by('title') #get games sorted alphabetically
    games_by_genre = {} #organize games by genre

    for game in Media.objects.filter(type='Game').prefetch_related('genres'): #group games by their genres
        for genre in game.genres.all():
            games_by_genre.setdefault(genre.name, []).append(game)

    context = { #prepare context data for template
        'media_list': games,
        'media_type': 'Games',
        'trending_movies': trending_games,
        'movies_alphabetically': games_alphabetically,
        'movies_by_genre': games_by_genre,
        'suggested_movies': suggested_games,
    }
    return render(request, 'ScreenCritic/media.html', context)

def media_detail(request, slug, media_type): #display detailed view of a specific media item
    media = get_object_or_404(Media, slug=slug, type=media_type) #get media object or return 404
    sort_option = request.GET.get('sort', 'likes-desc') #get sort parameter from request
    sort_field, sort_direction = sort_option.split('-') if '-' in sort_option else ('likes', 'desc')

    reviews = Review.objects.filter(media=media).annotate(
        likes_count=Count('reviewlike'))

    # Apply sorting based on field and direction
    if sort_field == 'likes':
        sort_prefix = '-' if sort_direction == 'desc' else ''
        reviews = reviews.order_by(f'{sort_prefix}likes_count', '-date')
    elif sort_field == 'rating':
        sort_prefix = '-' if sort_direction == 'desc' else ''
        reviews = reviews.order_by(f'{sort_prefix}rating', '-date')
    elif sort_field == 'date':
        sort_prefix = '-' if sort_direction == 'desc' else ''
        reviews = reviews.order_by(f'{sort_prefix}date')

    rating_stats = reviews.aggregate(total_ratings=Count('rating'), average_rating=Avg('rating'))
    total_ratings = rating_stats['total_ratings'] or 0
    average_rating = round(rating_stats['average_rating'] or 0,1)
    text_reviews_count = reviews.exclude(review__isnull=True).exclude(review__exact='').count()

    recommended_media = Media.objects.filter(type=media_type).exclude(slug=slug).annotate(
        avg_rating=Avg('review__rating')).order_by('-avg_rating')[:20]

    liked_reviews = set()
    if request.user.is_authenticated:
        liked_reviews = set(ReviewLike.objects.filter(user=request.user).values_list('review_id', flat=True))
    
    # Check if user has reviewed this media
    user_has_reviewed = False
    if request.user.is_authenticated:
        user_has_reviewed = Review.objects.filter(
            user=request.user,
            media=media
        ).exists()

    # Check if user is subscribed to this media
    is_subscribed = False
    if request.user.is_authenticated:
        is_subscribed = UserMediaSubscription.objects.filter(
            user=request.user,
            media=media
        ).exists()

    # Get today and tomorrow's date for comparison
    today = timezone.now().date()
    tomorrow = today + timezone.timedelta(days=1)

    # Check if media is future release
    is_future_release = media.release_date.date() > tomorrow if media.release_date else False

    context = {
        'media': media,
        'reviews': reviews,
        'recommended_media': recommended_media,
        'total_ratings': total_ratings,

templates/ScreenCritic/delete_account.html
{% extends 'ScreenCritic/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/delete_account.css' %}">

<div class="delete-account-container">
    <div class="delete-account-box">
        <h2>Delete Your Account</h2>
        
        <div class="warning-message">
            <p><strong>Warning:</strong> This action is permanent and cannot be undone.</p>
            <p>All of your data including reviews, ratings, and profile information will be permanently deleted.</p>
        </div>

        <form method="post" action="{% url 'ScreenCritic:delete_account' %}">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="id_password">Enter your password to confirm:</label>
                <input type="password" name="password" id="id_password" class="form-control" required>
                {% if form.password.errors %}
                    <div class="error">{{ form.password.errors }}</div>
                {% endif %}
            </div>

            <div class="confirmation-checkbox">
                <input type="checkbox" name="confirm_delete" id="id_confirm_delete" required>
                <label for="id_confirm_delete">I understand that this action cannot be undone</label>
            </div>

            <div class="button-group">
                <button type="submit" class="delete-button" id="deleteButton" disabled>Delete My Account</button>
                <a href="{% url 'ScreenCritic:profile' %}" class="cancel-button">Cancel</a>
            </div>
        </form>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const checkbox = document.getElementById('id_confirm_delete');
    const deleteButton = document.getElementById('deleteButton');
    
    checkbox.addEventListener('change', function() {
        deleteButton.disabled = !this.checked;
    });
});
</script>

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

{% endblock %}

templates/ScreenCritic/profile.html
{% extends "ScreenCritic/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title_block %}
<title>{{ user_profile.user.username }} - Profile</title>
<link rel="stylesheet" href="{% static 'css/profile.css' %}?v=999">
{% endblock %}

{% block content %}
{% csrf_token %}
<div class="profile-container">
    <!-- Sidebar with user info -->
    <div class="profile-sidebar">
        {% if user_profile.profile_picture %}
            <img class="profile-img" src="{{ user_profile.profile_picture|resolve_image }}" alt="Profile Picture">
        {% else %}
            <img class="profile-img" src="{% static 'images/default_profile.png' %}" alt="Default Profile">
        {% endif %}
        <h2>{{ user_profile.user.username }}</h2>

        <!-- Review count changes based on selected tab -->
        <p class="review-count">
            {% if active_tab == 'reviewed' %}
                {{ reviewed_reviews.count|default:0 }} Reviewed
            {% elif active_tab == 'liked' %}
                {{ liked_reviews.count|default:0 }} Liked
            {% elif active_tab == 'to-review' %}
                {{ to_review_media.count|default:0 }} To-Review
            {% endif %}
        </p>
        <!-- Bio -->
        <div class="bio-box">
            <h3>Bio</h3>
            <p>{{ user_profile.bio|default:"No bio yet." }}</p>
        </div>

        <!-- Favorite genres -->
        <div class="genre-box">
            <h3>Genres</h3>
            <ul>
                {% for fav in favorite_genres %}
                    <li>{{ fav.genre.name }}</li>
                {% empty %}
                    <li>No genres yet.</li>
                {% endfor %}
            </ul>
        </div>
        <!-- Edit buttons only on the users page -->
        {% if user == user_profile.user %}
            <a class="edit-btn" href="{% url 'ScreenCritic:edit_profile' %}">⚙️Edit Profile</a>
            <a class="edit-btn" href="{% url 'ScreenCritic:user_logout' %}">😢Logout</a>
            <a class="edit-btn" href="{% url 'ScreenCritic:delete_account' %}">❌Delete Account</a>
            <a class="edit-btn" href="{% url 'password_change' %}">🔓Change Password</a>
        {% endif %}
    </div>
    <!-- Main content: tabs and reviews -->
    <div class="profile-main">
        <div class="tab-nav">
            <a href="?tab=reviewed"{% if active_tab == 'reviewed' %} class="active"{% endif %}>Reviewed</a>
            <a href="?tab=liked"{% if active_tab == 'liked' %} class="active"{% endif %}>Liked</a>
            <a href="?tab=to-review"{% if active_tab == 'to-review' %} class="active"{% endif %}>To-Review</a>
        </div>

        {% if active_tab != 'to-review' %}
        <div class="sort-header-container">
            <div class="sort-header" data-sort="likes">
                <span>Likes</span>
                <span class="sort-arrow">
                    {% if current_sort == 'likes-desc' %}▼{% elif current_sort == 'likes-asc' %}▲{% endif %}
                </span>
            </div>
            <div class="sort-header" data-sort="rating">
                <span>Rating</span>
                <span class="sort-arrow">
                    {% if current_sort == 'rating-desc' %}▼{% elif current_sort == 'rating-asc' %}▲{% endif %}
                </span>
            </div>
            <div class="sort-header" data-sort="date">
                <span>Date</span>
                <span class="sort-arrow">
                    {% if current_sort == 'date-desc' %}▼{% elif current_sort == 'date-asc' %}▲{% endif %}
                </span>
            </div>
        </div>
        <input type="hidden" id="current-sort" value="{{ current_sort }}">
        <input type="hidden" name="tab" value="{{ active_tab }}">
        {% endif %}

        <!-- Scrollable review section -->
        <div class="review-scroll">
            <!-- reviewed tab-->
            {% if active_tab == 'reviewed' %}
                {% for review in page_obj %}
                <div class="review-card">
                    <!-- Media image with lazy loading -->
                    {% if review.media.slug %}
                        <a href="{% if review.media.type == 'TV Show' %}
                                    {% url 'ScreenCritic:tv_detail' slug=review.media.slug %}
                                 {% elif review.media.type == 'Movie' %}
                                    {% url 'ScreenCritic:movie_detail' slug=review.media.slug %}
                                 {% elif review.media.type == 'Game' %}
                                    {% url 'ScreenCritic:game_detail' slug=review.media.slug %}
                                 {% endif %}">
                            <img src="{{ review.media.cover_image|resolve_image }}" class="media-img" alt="{{ review.media.title }}" loading="lazy">
                        </a>
                    {% else %}
                        <img src="{{ review.media.cover_image|resolve_image }}" class="media-img" alt="{{ review.media.title }}" loading="lazy">
                    {% endif %}
                    <!-- Review detail-->
                    <div class="review-content">
                        <h4>{{ review.media.title }}</h4>
                        <div class="review-header">
                            <div class="review-user">
                                {% if review.user.userprofile.profile_picture %}
                                    <img src="{{ review.user.userprofile.profile_picture|resolve_image }}" class="profile-pic" alt="User Pic">
                                {% else %}
                                    <img src="{% static 'images/default_profile.png' %}" class="profile-pic" alt="Default Pic">
                                {% endif %}
                                <span class="username-plain">{{ review.user.username }}</span>
                            </div>
                            <span class="review-date">{{ review.date|date:"M d, Y" }}</span>
                        </div>
                        <div>Rated:
                            {% for i in "12345" %}
                                {% if forloop.counter <= review.rating %}★{% else %}☆{% endif %}
                            {% endfor %}
                        </div>
                        {% if review.review %}
                        <p>Comment: {{ review.review }}</p>
                        {% endif %}
                        <p>
                            <span class="like-btn {% if review.review_id in liked_reviews_ids %}liked{% endif %}" data-review-id="{{ review.review_id }}">
                                <i class="{% if review.review_id in liked_reviews_ids %}fa-solid{% else %}fa-regular{% endif %} fa-heart"></i>
                            </span>
                            <span id="like-count-{{ review.review_id }}">{{ review.reviewlike_set.count }}</span> Likes
                        </p>
                    </div>
                </div>
                {% empty %}
                <p>No reviews yet.</p>
                {% endfor %}

            <!-- liked reviews tab-->
            {% elif active_tab == 'liked' %}
                {% for review in page_obj %}
                <div class="review-card">
                    <!-- liked media with lazy loading -->
                    {% if review.media.slug %}
                        <a href="{% if review.media.type == 'TV Show' %}
                                    {% url 'ScreenCritic:tv_detail' slug=review.media.slug %}
                                 {% elif review.media.type == 'Movie' %}
                                    {% url 'ScreenCritic:movie_detail' slug=review.media.slug %}
                                 {% elif review.media.type == 'Game' %}
                                    {% url 'ScreenCritic:game_detail' slug=review.media.slug %}
                                 {% endif %}">
                            <img src="{{ review.media.cover_image|resolve_image }}" class="media-img" alt="{{ review.media.title }}" loading="lazy">
                        </a>
                    {% else %}
                        <img src="{{ review.media.cover_image|resolve_image }}" class="media-img" alt="{{ review.media.title }}" loading="lazy">
                    {% endif %}
                    <!-- Review content -->
                    <div class="review-content">
                        <h4>{{ review.media.title }}</h4>
                        <div class="review-header">
                            <div class="review-user">
                                <a href="{% url 'ScreenCritic:profile_by_username' username=review.user.username %}" class="profile-link">
                                {% if review.user.userprofile.profile_picture %}
                                    <img src="{{ review.user.userprofile.profile_picture|resolve_image }}" class="profile-pic" alt="User Pic">
                                {% else %}
                                    <img src="{% static 'images/default_profile.png' %}" class="profile-pic" alt="Default Pic">
                                {% endif %}
                                <span class="username-plain">{{ review.user.username }}</span>
                                </a>
                            </div>
                            <span class="review-date">{{ review.date|date:"M d, Y" }}</span>
                        </div>
                        <div>Rated:
                            {% for i in "12345" %}
                                {% if forloop.counter <= review.rating %}★{% else %}☆{% endif %}
                            {% endfor %}
                        </div>
                        <p>Comment: {{ review.review }}</p>
                        <p>
                            <span class="like-btn liked" data-review-id="{{ review.review_id }}">
                                <i class="fa-solid fa-heart"></i>
                            </span>
                            <span id="like-count-{{ review.review_id }}">{{ review.reviewlike_set.count }}</span> Likes
                        </p>
                    </div>
                </div>
                {% empty %}
                <p>No liked reviews yet.</p>
                {% endfor %}

            <!-- to-review tab -->
            {% elif active_tab == 'to-review' %}
                {% for media in page_obj %}
                <div class="review-card">
                    {% if media.slug %}
                        <a href="{% if media.type == 'TV Show' %}
                                    {% url 'ScreenCritic:tv_detail' slug=media.slug %}
                                 {% elif media.type == 'Movie' %}
                                    {% url 'ScreenCritic:movie_detail' slug=media.slug %}
                                 {% elif media.type == 'Game' %}
                                    {% url 'ScreenCritic:game_detail' slug=media.slug %}
                                 {% endif %}">
                            <img src="{{ media.cover_image|resolve_image }}" class="media-img" alt="{{ media.title }}" loading="lazy">
                        </a>
                    {% else %}
                        <img src="{{ media.cover_image|resolve_image }}" class="media-img" alt="{{ media.title }}" loading="lazy">
                    {% endif %}
                    <div class="review-content">
                        <h4>{{ media.title }}</h4>
                        <p>{{ media.description|truncatewords:25|safe }}</p>
                    </div>
                </div>
                {% empty %}
                <p>No recommendations yet.</p>
                {% endfor %}
            {% endif %}
        </div>

        <!-- Pagination block for reviewed liked and to-review  -->
        {% if active_tab == "reviewed" or active_tab == "liked" or active_tab == "to-review" %}
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a class="page-btn" href="?tab={{ active_tab }}&sort={{ current_sort }}&page={{ page_obj.previous_page_number }}">← Previous</a>
            {% endif %}
            <span class="page-number">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
            {% if page_obj.has_next %}
                <a class="page-btn" href="?tab={{ active_tab }}&sort={{ current_sort }}&page={{ page_obj.next_page_number }}">Next →</a>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
<!-- Like button functionality -->
<script src="{% static 'js/like.js' %}?v=3"></script>
<script src="{% static 'js/profile-sorting.js' %}?v=1"></script>
{% endblock %}